[package]
name = "lorri"
version = "0.1.0"
authors = [
  "Graham Christensen <graham.christensen@target.com>",
]
license = "Apache-2.0"

[dependencies]
structopt = "0.2"
log = "0.4"
env_logger= "0.6"
regex = "1.1.0"
lazy_static = "1.2.0"
futures = "0.1.25"
md5  = "0.6.1"
directories = "1.0.2"
notify = "4.0.6"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
bincode = "1.1.3"
tempfile = "3.0.7"
vec1 = "1.1.0"
proptest = "0.9.1"
